import { ORDER_STATUS, ROLES, DELIVERY_STATUS } from '../utils/constants.js';
import { ApiError } from '../utils/api.js';

export const ALLOWED_TRANSITIONS = {
  [ORDER_STATUS.PENDING]: [ORDER_STATUS.CONFIRMED, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.CONFIRMED]: [ORDER_STATUS.ACCEPTED, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.ACCEPTED]: [ORDER_STATUS.PREPARING, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.PREPARING]: [ORDER_STATUS.READY_FOR_PICKUP, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.READY_FOR_PICKUP]: [ORDER_STATUS.PICKED_UP, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.PICKED_UP]: [ORDER_STATUS.ON_THE_WAY],
  [ORDER_STATUS.ON_THE_WAY]: [ORDER_STATUS.DELIVERED],
  [ORDER_STATUS.DELIVERED]: [ORDER_STATUS.COMPLETED],
  [ORDER_STATUS.COMPLETED]: [],
  [ORDER_STATUS.CANCELLED]: [],
};

export const ROLE_TRANSITIONS = {
  [ROLES.CUSTOMER]: {
    [ORDER_STATUS.PENDING]: [ORDER_STATUS.CANCELLED],
    [ORDER_STATUS.CONFIRMED]: [ORDER_STATUS.CANCELLED],
    [ORDER_STATUS.ACCEPTED]: [ORDER_STATUS.CANCELLED],
  },
  [ROLES.SELLER]: {
    [ORDER_STATUS.CONFIRMED]: [ORDER_STATUS.ACCEPTED, ORDER_STATUS.CANCELLED],
    [ORDER_STATUS.ACCEPTED]: [ORDER_STATUS.PREPARING, ORDER_STATUS.CANCELLED],
    [ORDER_STATUS.PREPARING]: [ORDER_STATUS.READY_FOR_PICKUP, ORDER_STATUS.CANCELLED],
  },
  [ROLES.DELIVERY_PARTNER]: {
    [ORDER_STATUS.READY_FOR_PICKUP]: [ORDER_STATUS.PICKED_UP],
    [ORDER_STATUS.PICKED_UP]: [ORDER_STATUS.ON_THE_WAY],
    [ORDER_STATUS.ON_THE_WAY]: [ORDER_STATUS.DELIVERED],
  },
  [ROLES.ADMIN]: ALLOWED_TRANSITIONS,
  SYSTEM: {
    [ORDER_STATUS.PENDING]: [ORDER_STATUS.CONFIRMED, ORDER_STATUS.CANCELLED],
    [ORDER_STATUS.DELIVERED]: [ORDER_STATUS.COMPLETED],
  },
};

export function assertTransition(from, to, role) {
  const globallyAllowed = ALLOWED_TRANSITIONS[from] || [];
  if (!globallyAllowed.includes(to)) {
    throw new ApiError(400, `Cannot change status from ${from} to ${to}`);
  }
  const roleMap = ROLE_TRANSITIONS[role] || {};
  const roleAllowed = roleMap[from] || [];
  if (!roleAllowed.includes(to)) {
    throw new ApiError(403, `${role} cannot change status from ${from} to ${to}`);
  }
}

export const ORDER_TO_DELIVERY = {
  [ORDER_STATUS.PICKED_UP]: DELIVERY_STATUS.PICKED_UP,
  [ORDER_STATUS.ON_THE_WAY]: DELIVERY_STATUS.ON_THE_WAY,
  [ORDER_STATUS.DELIVERED]: DELIVERY_STATUS.DELIVERED,
  [ORDER_STATUS.CANCELLED]: DELIVERY_STATUS.CANCELLED,
};
